version: "3.9"

services:
  db:
    container_name: fastapi-db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    hostname: postgres

volumes:
  test-volume:
    name: postgres-fastapi
